apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: demo-chatbot-june16
  janus-idp.io/tekton: demo-chatbot-june16
  backstage.io/kubernetes-id: demo-chatbot-june16
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: demo-chatbot-june16
resources:
  - application-dev.yaml