apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: demo-chatbot-june16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-chatbot-june16
  name: demo-chatbot-june16
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
