apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: demo-chatbot-june16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-chatbot-june16
  name: demo-chatbot-june16
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo-chatbot-june16
    weight: 100
  wildcardPolicy: None
