apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: demo-chatbot-june16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-chatbot-june16
  name: demo-chatbot-june16
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: demo-chatbot-june16
