apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: demo-chatbot-june16
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/demo-chatbot-june16:8e394c1fff4945f92758fbb4fa71e6b61fe4e7b1@sha256:21a67bcc58dae61ebddc567a27be6ef038164d4b40b0cb0405207bd1071551be # use pre-built to bootstrap
          name: app-inference
